### ISSUE TITLE
Allow to disable autofocus for search input 

### ISSUE THREAD

**Issue by rsmything** [jshjohnson/Choices#94] opened 2017-01-05 10:10 UTC
Hello, it is not convenient when the phone keypad appears when you open the drop-down menu.

Now there isn't option to disable autofocus, only if disable search completely, can you add global option to setup "focusInput" (false/true)

    if (focusInput && this.canSearch && document.activeElement !== this.input) {
      this.input.focus();
    }

Thx

**Comment by jshjohnson** [comment] 2017-01-05 10:17
Hi @rsmything,

How would you envisage searching options if you had auto-focussing disabled? 

Thanks, 
Josh

**Comment by jshjohnson** [comment] 2017-01-05 10:41
Ah I see what you mean. That should be a simple change to make - I'm happy to review a pull request for this :)

**Comment by rsmything** [comment] 2017-01-05 10:56
Thx,
so, more one a question, how to handle advanced parameters from json, example:

[
  {
    "choices": [
      {
        "disabled": true,
        "selected": true,
        "text": "Please select a tracker",
        "value": "Please select a tracker"
      }
    ],
    "label": ""
  },
  {
    "choices": [
      {
        "text": "Visa Tracker - SC189",
        "value": "/au/trackers/visa-tracker-sc189-custom/cases/new"
      },
      {
        "text": "Visa Tracker - SC190",
        "value": "/au/trackers/visa-tracker-sc190/cases/new"
      },
      {
        "text": "adad",
        "value": "/au/trackers/adad-subtracker/cases/new"
      },
      {
        "text": "1421",
        "value": "/au/trackers/1421/cases/new"
      }
    ],
    "label": "Australia"
  },
  {
    "choices": [
      {
        "text": "Roma's tracker",
        "value": "/ca/trackers/romas-tracker/cases/new"
      }
    ],
    "label": "Canada"
  },
  {
    "choices": [
      {
        "text": "31313131",
        "value": "/us/trackers/31313131/cases/new"
      }
    ],
    "label": "United States of America"
  }
]

**Now i need to parse country from "value" for custom template**

want =)
      {
        "text": "31313131",
        "value": "/us/trackers/31313131/cases/new",
        **"country" "au"**
      }

and handle this to setChoices()

**Comment by jshjohnson** [comment] 2017-08-03 15:51
Closing this as focusing/blurring the input is how Choices determines an active dropdown.

**Closed by jshjohnson** 2017-08-03 15:51 UTC
Labels: accepting PRs, difficulty:complex, feature request

**Comment by Flowgram** [comment] 2019-03-21 14:00
Hey @jshjohnson, so just to confirm, there's no way to not focus on the input box when opening the options?

The issue is really on mobile where the keyboard opens up, which is not really what the user would expect from tapping on a select drop-down.

**Comment by nlaitan** [comment] 2020-02-26 15:40
Agree to @Flowgram, the keyboard opened it's quite annoying and brings usability problems

**Comment by raduchiriac** [comment] 2021-04-29 19:25
> the keyboard opened it's quite annoying and brings usability problems

If you don't need the search functionality you can do something like this and the keyboard won't open:
```javascript
for (const element of [...document.querySelectorAll("input.choices__input")]) {
  element.setAttribute("disabled", "true");
}
```
