### ISSUE TITLE
clearChoices() / removeItems() does not reset store.items

### ISSUE THREAD

**Issue by adilyalcin** [jshjohnson/Choices#773] opened 2019-11-23 21:25 UTC
Hi!

I'd like to file a bug report / undesired behavior when updating choices object (multiple-select view with active items shown as pills/boxes) using **setChoices**.

I need to update the full set of choices and selected items frequently in an application.
For that, I used setChoices(). I call "removeActiveItems" beforehand as I realized the old active items are not removed on this reset.

However, after resetting the options this way, the selected items in the new setChoices option appear multiple times (the "pills" boxes on input area), even though the options are listed once in the input.

I traced the issue in choices.js source code.

The problem is, this.store.items is *not* reset to an empty list properly after setChoices (or removeActiveItems). There's *residue* of previous selections that remain after such reset.

I think the fix would update "clearChoices" function to also remove all active and not-active items. I already had to add "removeActiveItems" to make it reset properly on single-choice case. With multiple-choice input, repetition of a selected item is an important bug.

For now, I'll choose to destroy & re-init the object, but if there's an improvement on this bug / unexpected behavior, that'd be great.

Thanks!

**Comment by jshjohnson** [comment] 2019-11-28 18:50
Could you not use `clearStore` here @adilyalcin?

**Comment by jshjohnson** [comment] 2019-11-28 21:26
Closing as this is a duplicate of #751 - see this PR for progress on a fix: https://github.com/jshjohnson/Choices/pull/787

**Closed by jshjohnson** 2019-11-28 21:26 UTC
Labels: bug
