### ISSUE TITLE
Destroy doesn't put original select back

### ISSUE THREAD

**Issue by SampsonCrowley** [jshjohnson/Choices#298] opened 2017-12-01 21:52 UTC
Scenario I have a normal select box with class 'searchable' and normal html options (no ajax).

a choices instance is created:

```js
choices = new Choices('select.searchable')
```

I destroy the choices instance

```js
choices.destroy()
```

NOW, the Docs say that my select tag should be back to its original state.

HOWEVER instead, the select box is left blank (i.e no options in list)

**Comment by jshjohnson** [comment] 2017-12-05 13:54
Hey are you able to send me a JSFiddle or a Codepen highlighting the problem please?

**Comment by SampsonCrowley** [comment] 2017-12-08 01:04
I will when I get some free time. Currently I'm just storing the options for every select before it's instantiated, then putting the original back from my own variables

**Comment by DonGissel** [comment] 2017-12-11 10:03
I can easily reproduce this as well. It's very inconvenient! Here ya go:

https://jsfiddle.net/5ggLd0kp/

**Comment by SampsonCrowley** [comment] 2017-12-13 01:23
@DonGissel yep that is exactly the issue. Nice and concise fiddle

**Comment by jshjohnson** [comment] 2017-12-15 09:31
Thanks for the jsfiddle. This isn't so much a bug as it is a missing piece of functionality! 

Out of interest, would you expect `destroy()` to restore select options as they were *before* Choices was initiated? Or would you expect it to create options based on the state of Choices - including which options have been selected etc?

**Comment by DonGissel** [comment] 2017-12-15 10:18
Well, it emptying the original `<select>` I would very much classify as a bug. ;-)

That being said, I can see valid points for both restoring original state and persisting the new state. Perhaps a boolean option could be passed to `destroy()` to determine whether or not to update the original element, with the default being not to (`false`)?

**Comment by SampsonCrowley** [comment] 2017-12-18 19:52
I would say this is definitely classified as a bug, since the Docs say that on destroy, the element is put back to its *original* state

as for whether is should revert back to original, or new persisted state, the default in my opinion for a **destroy** function should be the *original* state

A flag to persist the current state would be helpful however

**Comment by warrebuysse** [comment] 2018-05-26 09:08
@jshjohnson What is the progress on this?

**Comment by jshjohnson** [comment] 2018-05-27 15:47
This has been fixed on the `develop` branch and will go out in the next release 👍

**Closed by jshjohnson** 2018-05-27 15:47 UTC
Labels: bug, difficulty:easy, in progress

**Comment by smoockpp** [comment] 2018-08-23 15:00
When that release is planned to happen... quite keen to get that functionality working, otherwise I'll have to fork it and do it myself

**Comment by DV8FromTheWorld** [comment] 2018-09-08 01:51
I also need this functionality to be released.

**Comment by perifer** [comment] 2019-03-21 13:55
This seems to be an issue in 6.0.3, see updated example: https://jsfiddle.net/pco03evt/

Should this be re-opened?

**Comment by filip-jk** [comment] 2019-11-14 17:36
This is still a glitch in 8.0.0...

**Comment by jshjohnson** [comment] 2019-11-14 20:36
> This is still a glitch in 8.0.0...

See https://github.com/jshjohnson/Choices/pull/574
