### ISSUE TITLE
Load remote by autocomplete

### ISSUE THREAD

**Issue by kamov** [jshjohnson/Choices#446] opened 2018-10-10 04:27 UTC
I see there is way to fetch data from remote.
However, it load all after page load.
I would like to fetch when user start typing, and data are populated after user type words.

It's possible?

I also notice that if I add selected items (with multiple) this are loaded also double.

The option duplicated items seem not work.

My code:

```js
let choicesUsers = new Choices('#js-choices-users', {
    duplicateItems: false
});

choicesUsers.ajax((callback) => {
    fetch('/admin/getUsers')
        .then((response) => {
            response.json().then(function(data) {
                callback(data, 'id', 'name');
            });
        })
        .catch((error) => {
            callback();
        });
});
```

**Comment by ezerr** [comment] 2018-10-21 05:10
I had the same problem of wanting to delay the request. The problem is that the `ajax()` function (AFAIK) could not delay the request a few milliseconds to wait for the rest of the user input.

Staying within the Choices framework as best as I could, I created the below. The only downside to this approach is that you have to define your own AJAX call.

````
// define the options that I wanted
var config = {
  'searchResultLimit': 15, // increases default limit
  'searchChoices': false // set to false if you don't want Choices to search for you
};
// selector; target the select by the id
var select = document.getElementById('mySelect');
// create the Choice instance with the selector and configuration object
var choice = new window.Choices(select, config);
// create a "search" event listener on the selector; this triggers when the user types
select.addEventListener('search', function(event) {
  // if a value is present
  if (event.detail.value) {
    // your AJAX request, whatever it is below
   getMyAjaxResults(function(response) {
     // set the choices; the "true" at the end prevents duplicate results
     select.setChoices(response, 'titleKey', 'labelKey', true);
  }
}
````

I hope this helps you and others.

**Comment by jshjohnson** [comment] 2018-10-28 10:33
Closing as solution has been given :)

**Closed by jshjohnson** 2018-10-28 10:33 UTC
