### ISSUE TITLE
addItems on select-multiple?

### ISSUE THREAD

**Issue by rstacruz** [jshjohnson/Choices#70] opened 2016-11-07 08:03 UTC
I'd love to have the preset options of select-multiple:

![image](https://cloud.githubusercontent.com/assets/74385/20050334/b173dd9e-a503-11e6-8484-d4164377680b.png)

Yet have the flexibility to add more items with `addItems: true`:

![image](https://cloud.githubusercontent.com/assets/74385/20050341/bb565832-a503-11e6-8fed-b7eb0022a3ac.png)

But `addItems` is only available for text inputs. What options do I have? Is that something I can help hack together?

**Comment by jshjohnson** [comment] 2016-11-07 09:54
Closing as this is a duplicate of https://github.com/jshjohnson/Choices/issues/39 👍

**Closed by jshjohnson** 2016-11-07 09:54 UTC
